apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gitlab
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-gitlab/releases/download/v0.1.0/gitlab_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./gitlab"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gitlab"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-gitlab/releases/download/v0.1.0/gitlab_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./gitlab"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gitlab"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/sunny0826/kubectl-gitlab/releases/download/v0.1.0/gitlab_windows_amd64.zip
    sha256: ""
    files:
    - from: "/gitlab.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "gitlab.exe"
  shortDescription: A new plugin
  homepage: https://github.com/sunny0826/kubectl-gitlab
  caveats: |
    Usage:
      $ kubectl gitlab

    For additional options:
      $ kubectl gitlab --help
      or https://github.com/sunny0826/kubectl-gitlab/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
